# Generated by Django 6.1.1 on 2026-09-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('date_event', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Finalizado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCapacity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('date', models.DateField()),
                ('total_hours_assigned', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
            options={
                'unique_together': {('user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('scheduled_date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Hecho'), ('postponed', 'Pospuesto')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='events.activity')),
            ],
        ),
    ]
